# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wmt9IwLc314_V6KxCeYVPutwxt8I2Utr
"""

x = [int (i) for i in input ('Enter The Integer Values').split()]
s=0
for j in x:
 s+=j
print(s)